```rust
// src/components/modal.rs
use leptos::*;
use web_sys::HtmlDivElement;

/// Props for the `Modal` component.
#[derive(Clone, Debug, PartialEq)]
pub struct ModalProps {
    /// Title displayed at the top of the modal.
    pub title: String,
    /// Content of the modal. Typically a view generated by other components.
    pub children: ChildrenFn,
    /// Callback fired when the user clicks the close button or the overlay.
    pub on_close: Option<Callback<()>>,
    /// Whether the modal is open (visible). If `None`, the component manages its own state.
    pub open: Option<bool>,
}

#[component]
pub fn Modal(
    cx: Scope,
    #[prop(optional)] title: String,
    #[prop(into)] children: ChildrenFn,
    #[prop(optional)] on_close: Option<Callback<()>>,
    #[prop(optional, default = None)] open: Option<bool>,
) -> impl IntoView {
    // Internal state if the parent does not control visibility.
    let (internal_open, set_internal_open) = create_signal(cx, true);
    let is_open = Signal::derive(move || open.unwrap_or_else(|| internal_open.get()));

    // Close handler
    let close = move |_| {
        if let Some(cb) = &on_close {
            cb.emit(());
        }
        set_internal_open.set(false);
    };

    view! { cx,
        <Show when=is_open fallback=move || ()>
            <div class="modal-overlay" on:click=close></div>
            <div class="modal-glass">
                <header class="modal-header">
                    <h2 class="modal-title">{title}</h2>
                    <button class="modal-close" aria-label="Close" on:click=close>"✕"</button>
                </header>
                <section class="modal-body">
                    {children(cx)}
                </section>
            </div>
        </Show>
    }
}
```

```css
/* src/components/modal.css */
.modal-overlay {
    position: fixed;
    inset: 0;
    background: rgba(0, 0, 0, 0.45);
    backdrop-filter: blur(4px);
    z-index: 999;
    animation: fadeIn 200ms ease-out forwards;
}

.modal-glass {
    position: fixed;
    top: 50%;
    left: 50%;
    width: min(90%, 500px);
    max-height: 80vh;
    transform: translate(-50%, -50%);
    background: rgba(30, 30, 35, 0.45);
    border-radius: 12px;
    box-shadow: 0 8px 32px rgba(0, 0, 0, 0.6);
    backdrop-filter: blur(12px) saturate(150%);
    -webkit-backdrop-filter: blur(12px) saturate(150%);
    border: 1px solid rgba(255, 255, 255, 0.18);
    overflow: hidden;
    z-index: 1000;
    display: flex;
    flex-direction: column;
    animation: slideDown 250ms cubic-bezier(.25,.8,.25,1) forwards;
}

.modal-header {
    padding: 1rem 1.2rem;
    background: rgba(255, 255, 255, 0.08);
    display: flex;
    align-items: center;
    justify-content: space-between;
    border-bottom: 1px solid rgba(255,255,255,0.12);
}

.modal-title {
    margin: 0;
    font-size: 1.25rem;
    color: #e0e0e0;
}

.modal-close {
    background: transparent;
    border: none;
    color: #c5c5c5;
    font-size: 1.2rem;
    cursor: pointer;
    transition: transform 150ms ease, color 150ms ease;
}
.modal-close:hover {
    color: #ff6b6b;
    transform: rotate(90deg);
}

.modal-body {
    padding: 1rem 1.2rem;
    overflow-y: auto;
    color: #d0d0d0;
}

/* Animations */
@keyframes fadeIn {
    from { opacity: 0; }
    to   { opacity: 1; }
}
@keyframes slideDown {
    from {
        opacity: 0;
        transform: translate(-50%, -60%);
    }
    to {
        opacity: 1;
        transform: translate(-50%, -50%);
    }
}

/* Dark theme tweaks */
@media (prefers-color-scheme: dark) {
    .modal-glass {
        background: rgba(20, 20, 25, 0.55);
    }
}
```

```rust
// src/main.rs (excerpt showing usage)
mod components;
use components::modal::*;
use leptos::*;

fn main() {
    // Initialize Leptos app...
}

// Example component using the Modal
#[component]
fn Demo(cx: Scope) -> impl IntoView {
    let show_modal = create_signal(cx, true);

    view! { cx,
        <Show when=move || show_modal.get() fallback=|| ()>
            <Modal
                title="Welcome to Trinity AI OS"
                on_close=Some(Callback::new(move |_| show_modal.set(false)))
            >
                <p>"This is a glass‑morphic modal with dark theme and smooth hover animations."</p>
                <button class="btn-primary" on:click=move |_| log!("Action performed")>
                    "Do something"
                </button>
            </Modal>
        </Show>
    }
}
```

```toml
# Cargo.toml (relevant dependencies)
[dependencies]
leptos = { version = "0.6", features = ["csr"] }
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["HtmlDivElement"] }
```

```scss
/* src/style.scss (global import) */
@import "./components/modal.css";

/* Optional button styling for the demo */
.btn-primary {
    background: rgba(255, 255, 255, 0.12);
    color: #e0e0e0;
    border: none;
    padding: 0.6rem 1rem;
    border-radius: 8px;
    cursor: pointer;
    transition: background 200ms ease, transform 150ms ease;
}
.btn-primary:hover {
    background: rgba(255, 255, 255, 0.2);
    transform: translateY(-2px);
}
```